

export const DEPT_COLORS = {
  Camera: "#333333",
  Grip: "#555555",
  Lighting: "#000000",
  Others: "#888888",
};


export const DEFAULT_DEPARTMENTS = {
  Grip: ["Dolly/Track", "Crane/Jib", "Rigging"],
  Camera: ["Cinema Bodies", "Mirrorless", "Special", "Filters", "Wireless Video", "Monitors"],
  Lenses: ["Spericals", "Zoom", "Anamorphics", "Probe & Macro", "Sony GM"],
  Lighting: ["HMI", "Tungsten", "LED", "Modifiers", "Special"],
  Others: ["Cinema Bodies"],
  Subrent: [],
};


export const DEFAULT_BRANDS = ["ARRI", "RED", "SONY", "FUJIFILM", "BLACKMAGIC", "GOPRO", "DJI", "VAXIS", "ACCSOON", "ARRI/ZEISS", "COOKE", "ZEISS", "DZOFILMS", "THYPOCH", "LAOWA", "BLAZAR", "DEDOLIGHT", "SKYPANEL", "APUTURE", "AMARAN", "PDL", "NISI", "ATOMOS", "HOLLYLAND"];


export const DEFAULT_CATALOG = [
  { id: "b3b87k1n", name: "PANTHER", brand: "", model: "PANTHER", department: "Grip", subcategory: "Dolly/Track", note: "" },
  { id: "qk76t2uc", name: "DOORWAY DOLLY", brand: "", model: "DOORWAY DOLLY", department: "Grip", subcategory: "Dolly/Track", note: "" },
  { id: "sv7o1xma", name: "DANA DOLLY/SLIDER", brand: "", model: "DANA DOLLY/SLIDER", department: "Grip", subcategory: "Dolly/Track", note: "" },
  { id: "ijh6a6c7", name: "UBANGI", brand: "", model: "UBANGI", department: "Grip", subcategory: "Dolly/Track", note: "" },
  { id: "qs8zhcpc", name: "CRANE", brand: "", model: "CRANE", department: "Grip", subcategory: "Crane/Jib", note: "" },
  { id: "607jw2l2", name: "JIB ARM", brand: "", model: "JIB ARM", department: "Grip", subcategory: "Crane/Jib", note: "" },
  { id: "couao6fh", name: "HELMET CAM", brand: "", model: "HELMET CAM", department: "Grip", subcategory: "Rigging", note: "" },
  { id: "g5n4u0v2", name: "SNORRI CAM", brand: "", model: "SNORRI CAM", department: "Grip", subcategory: "Rigging", note: "" },
  { id: "cjomf5uu", name: "ARRI 35", brand: "ARRI", model: "35", department: "Camera", subcategory: "Cinema Bodies", note: "S35" },
  { id: "tdlqo6sw", name: "ARRI MINI", brand: "ARRI", model: "MINI", department: "Camera", subcategory: "Cinema Bodies", note: "S35" },
  { id: "lyewyvtg", name: "ARRI MINI LF", brand: "ARRI", model: "MINI LF", department: "Camera", subcategory: "Cinema Bodies", note: "FF" },
  { id: "cun5eck4", name: "RED RAPTOR-VV", brand: "RED", model: "RAPTOR-VV", department: "Camera", subcategory: "Cinema Bodies", note: "VV" },
  { id: "vyid9aj1", name: "RED KOMODO", brand: "RED", model: "KOMODO", department: "Camera", subcategory: "Cinema Bodies", note: "S35" },
  { id: "qzyoefe8", name: "RED KOMODO-X", brand: "RED", model: "KOMODO-X", department: "Camera", subcategory: "Cinema Bodies", note: "S35" },
  { id: "98gi9zdp", name: "SONY VENICE 2", brand: "SONY", model: "VENICE 2", department: "Camera", subcategory: "Cinema Bodies", note: "FF" },
  { id: "k9n8t01v", name: "SONY VENICE", brand: "SONY", model: "VENICE", department: "Camera", subcategory: "Cinema Bodies", note: "FF" },
  { id: "70vionyf", name: "SONY BURANO", brand: "SONY", model: "BURANO", department: "Camera", subcategory: "Cinema Bodies", note: "FF" },
  { id: "4cphsyel", name: "FUJIFILM ETERNA", brand: "FUJIFILM", model: "ETERNA", department: "Camera", subcategory: "Cinema Bodies", note: "65" },
  { id: "1rlxakt6", name: "BLACKMAGIC URSA CINE 12K", brand: "BLACKMAGIC", model: "URSA CINE 12K", department: "Camera", subcategory: "Cinema Bodies", note: "FF" },
  { id: "6ytcxem2", name: "BLACKMAGIC URSA CINE 17K", brand: "BLACKMAGIC", model: "URSA CINE 17K", department: "Camera", subcategory: "Cinema Bodies", note: "65" },
  { id: "0vn9qqlt", name: "BLACKMAGIC PYXIS 6K", brand: "BLACKMAGIC", model: "PYXIS 6K", department: "Camera", subcategory: "Cinema Bodies", note: "FF" },
  { id: "ravm4oba", name: "BLACKMAGIC PYXIS 12K", brand: "BLACKMAGIC", model: "PYXIS 12K", department: "Camera", subcategory: "Cinema Bodies", note: "FF" },
  { id: "kxa62vdd", name: "SONY FX3", brand: "SONY", model: "FX3", department: "Camera", subcategory: "Mirrorless", note: "FF" },
  { id: "rbv435kl", name: "SONY FX5", brand: "SONY", model: "FX5", department: "Camera", subcategory: "Mirrorless", note: "FF" },
  { id: "muh4f14q", name: "SONY FX6", brand: "SONY", model: "FX6", department: "Camera", subcategory: "Mirrorless", note: "FF" },
  { id: "2pu5zvl6", name: "SONY FX9", brand: "SONY", model: "FX9", department: "Camera", subcategory: "Mirrorless", note: "FF" },
  { id: "nyp9jbqe", name: "GOPRO HERO 11", brand: "GOPRO", model: "HERO 11", department: "Camera", subcategory: "Special", note: "" },
  { id: "krivwz0j", name: "DJI ACTION CAM 4", brand: "DJI", model: "ACTION CAM 4", department: "Camera", subcategory: "Special", note: "" },
  { id: "1rtc3gij", name: "FSND 4×5.65″", brand: "", model: "FSND 4×5.65″", department: "Camera", subcategory: "Filters", note: "" },
  { id: "874q507j", name: "BLACK PROMIST 4×5.65″", brand: "", model: "BLACK PROMIST 4×5.65″", department: "Camera", subcategory: "Filters", note: "" },
  { id: "4gwv1rhz", name: "BLACKMAGIC 4×5.65″", brand: "", model: "BLACKMAGIC 4×5.65″", department: "Camera", subcategory: "Filters", note: "" },
  { id: "gk6vinb5", name: "BLUE STREAK 4×5.65″", brand: "", model: "BLUE STREAK 4×5.65″", department: "Camera", subcategory: "Filters", note: "" },
  { id: "3lqdcpa2", name: "STAR BURST 4×5.65″", brand: "", model: "STAR BURST 4×5.65″", department: "Camera", subcategory: "Filters", note: "" },
  { id: "ea0he9px", name: "RAINBOW 4×5.65″", brand: "", model: "RAINBOW 4×5.65″", department: "Camera", subcategory: "Filters", note: "" },
  { id: "1wmg5cyc", name: "NISI VND", brand: "NISI", model: "VND", department: "Camera", subcategory: "Filters", note: "" },
  { id: "h6z7gjs5", name: "NISI MIST FILTER", brand: "NISI", model: "MIST FILTER", department: "Camera", subcategory: "Filters", note: "" },
  { id: "yjl3yf1h", name: "VAXIS STORM", brand: "VAXIS", model: "STORM", department: "Camera", subcategory: "Wireless Video", note: "" },
  { id: "spzngley", name: "ACCSOON CINEVIEW SE", brand: "ACCSOON", model: "CINEVIEW SE", department: "Camera", subcategory: "Wireless Video", note: "" },
  { id: "rewy51o6", name: "ACCSOON CINEVIEW MASTER", brand: "ACCSOON", model: "CINEVIEW MASTER", department: "Camera", subcategory: "Wireless Video", note: "" },
  { id: "rjjyj5ys", name: "15\"-18\" MONITORS", brand: "", model: "15\"-18\" MONITORS", department: "Camera", subcategory: "Monitors", note: "" },
  { id: "lji1lhe8", name: "ATOMOS SHOGUN", brand: "ATOMOS", model: "SHOGUN", department: "Camera", subcategory: "Monitors", note: "Record/Playback" },
  { id: "79o5qar3", name: "ARRI SIGNATURE PRIMES", brand: "ARRI", model: "SIGNATURE PRIMES", department: "Lenses", subcategory: "Spericals", note: "LPL T1.8 FF OD 114mm" },
  { id: "iy26twto", name: "ARRI/ZEISS MASTER PRIMES", brand: "ARRI/ZEISS", model: "MASTER PRIMES", department: "Lenses", subcategory: "Spericals", note: "PL T1.3 S35 OD 114mm" },
  { id: "ln5zfpzh", name: "ARRI/ZEISS ULTRA PRIMES", brand: "ARRI/ZEISS", model: "ULTRA PRIMES", department: "Lenses", subcategory: "Spericals", note: "PL T1.9 S35 OD 95mm" },
  { id: "a7h8z3kg", name: "ARRI/ZEISS SUPER SPEED MK III", brand: "ARRI/ZEISS", model: "SUPER SPEED MK III", department: "Lenses", subcategory: "Spericals", note: "PL T1.3 S35 OD 80mm" },
  { id: "ot6kitzi", name: "ARRI/ZEISS SUPER SPEED MK II", brand: "ARRI/ZEISS", model: "SUPER SPEED MK II", department: "Lenses", subcategory: "Spericals", note: "PL T1.3 S35" },
  { id: "xe8x5wny", name: "COOKE S8/I FF PRIMES", brand: "COOKE", model: "S8/I FF PRIMES", department: "Lenses", subcategory: "Spericals", note: "PL T1.4 FF OD 104mm" },
  { id: "9vgjkf37", name: "COOKE S7/I FF", brand: "COOKE", model: "S7/I FF", department: "Lenses", subcategory: "Spericals", note: "PL T2 FF OD 110mm" },
  { id: "1kajx7y7", name: "COOKE 5/I", brand: "COOKE", model: "5/I", department: "Lenses", subcategory: "Spericals", note: "PL T1.4 S35 OD 110mm" },
  { id: "90vkp6tr", name: "COOKE S4/I PRIMES", brand: "COOKE", model: "S4/I PRIMES", department: "Lenses", subcategory: "Spericals", note: "PL T2 S35" },
  { id: "c39swfl6", name: "COOKE SP3", brand: "COOKE", model: "SP3", department: "Lenses", subcategory: "Spericals", note: "E/RF/M/Z/L T2.4 FF OD 64mm" },
  { id: "87c2n9s1", name: "ZEISS SUPREME PRIMES", brand: "ZEISS", model: "SUPREME PRIMES", department: "Lenses", subcategory: "Spericals", note: "PL T1.5 FF OD 95mm" },
  { id: "rczvwu64", name: "DZOFILMS VESPID PRIME 2", brand: "DZOFILMS", model: "VESPID PRIME 2", department: "Lenses", subcategory: "Spericals", note: "PL T1.9 VV/FF OD 80mm" },
  { id: "lcdoiieh", name: "DZOFILMS VESPID PRIME OG", brand: "DZOFILMS", model: "VESPID PRIME OG", department: "Lenses", subcategory: "Spericals", note: "PL T2.1 VV/FF OD 80mm" },
  { id: "7bk11mtt", name: "DZOFILMS ARLES PRIMES", brand: "DZOFILMS", model: "ARLES PRIMES", department: "Lenses", subcategory: "Spericals", note: "PL T1.4 VV/FF OD 95mm" },
  { id: "dwlr1hr6", name: "THYPOCH SIMERA-C", brand: "THYPOCH", model: "SIMERA-C", department: "Lenses", subcategory: "Spericals", note: "R/M T1.5 FF OD 67mm" },
  { id: "3weqr5tz", name: "LAOWA 9MM", brand: "LAOWA", model: "9MM", department: "Lenses", subcategory: "Spericals", note: "PL/E/Z/RF/L T5.8 VV OD 80mm" },
  { id: "czaddkcq", name: "LAOWA 10MM ZERO-D CINE", brand: "LAOWA", model: "10MM ZERO-D CINE", department: "Lenses", subcategory: "Spericals", note: "PL/LPL/E/Z/RF/L T2.9 FF/VV OD 80mm" },
  { id: "cb2yzx0o", name: "LAOWA 12MM ZERO-D CINE", brand: "LAOWA", model: "12MM ZERO-D CINE", department: "Lenses", subcategory: "Spericals", note: "PL/E/Z/RF/L T2.9 FF/VV OD 80mm" },
  { id: "r6fo0wvf", name: "LAOWA 8-15MM", brand: "LAOWA", model: "8-15MM", department: "Lenses", subcategory: "Zoom", note: "PL T2.9  FF" },
  { id: "t37ulmjv", name: "DZOFILMS CATTA ACE", brand: "DZOFILMS", model: "CATTA ACE", department: "Lenses", subcategory: "Zoom", note: "PL 18-35/35-80/70-135 T2.9 VV/FF OD 80m" },
  { id: "j4uzssgo", name: "DZOFILMS ARLES ZOOM", brand: "DZOFILMS", model: "ARLES ZOOM", department: "Lenses", subcategory: "Zoom", note: "PL 25-75/65-180 T2.6 VV/FF OD 80m" },
  { id: "a38s3ejr", name: "COOKE ANAMORPHIC/I S35", brand: "COOKE", model: "ANAMORPHIC/I S35", department: "Lenses", subcategory: "Anamorphics", note: "PL T2.3 S35" },
  { id: "40g9k4y1", name: "COOKE ANAMORPHIC/I FF", brand: "COOKE", model: "ANAMORPHIC/I FF", department: "Lenses", subcategory: "Anamorphics", note: "PL T2.3 FF OD 110mm" },
  { id: "690v48k7", name: "LAOWA PROTEUS 2X", brand: "LAOWA", model: "PROTEUS 2X", department: "Lenses", subcategory: "Anamorphics", note: "PL T2 FF OD 114mm" },
  { id: "neojud4n", name: "DZOFILMS PAVO 2X", brand: "DZOFILMS", model: "PAVO 2X", department: "Lenses", subcategory: "Anamorphics", note: "PL T2.1 S35 OD 95m" },
  { id: "2axm7rdk", name: "DZOFILMS ARCANA 2X", brand: "DZOFILMS", model: "ARCANA 2X", department: "Lenses", subcategory: "Anamorphics", note: "PL T2.1 VV/FF OD 80m" },
  { id: "8bthy91b", name: "BLAZAR VIPER 1.5X", brand: "BLAZAR", model: "VIPER 1.5X", department: "Lenses", subcategory: "Anamorphics", note: "PL T2.1 FF OD 80mm" },
  { id: "cdwjhrof", name: "BLAZAR REMUS 1.5X", brand: "BLAZAR", model: "REMUS 1.5X", department: "Lenses", subcategory: "Anamorphics", note: "PL T1.8 FF OD 80mm" },
  { id: "meue8zbg", name: "DZOFILMS X-TRACT 18-28 SET", brand: "DZOFILMS", model: "X-TRACT 18-28 SET", department: "Lenses", subcategory: "Probe & Macro", note: "PL T8 FF" },
  { id: "ejbplwiq", name: "LAOWA PROBE ZOOM SET", brand: "LAOWA", model: "PROBE ZOOM SET", department: "Lenses", subcategory: "Probe & Macro", note: "PL 15-35mm T12 15-24mm T8 FF" },
  { id: "0iiamqib", name: "LAOWA PRO2BE 24MM 2X MARO", brand: "LAOWA", model: "PRO2BE 24MM 2X MARO", department: "Lenses", subcategory: "Probe & Macro", note: "PL T8 FF" },
  { id: "vqt7b3m5", name: "SONY 12-24MM F2.8", brand: "SONY", model: "12-24MM F2.8", department: "Lenses", subcategory: "Sony GM", note: "" },
  { id: "vwofhqzg", name: "SONY 16-35MM F2.8 II", brand: "SONY", model: "16-35MM F2.8 II", department: "Lenses", subcategory: "Sony GM", note: "T82" },
  { id: "8v18txdc", name: "SONY 24-70MM F2.8 II", brand: "SONY", model: "24-70MM F2.8 II", department: "Lenses", subcategory: "Sony GM", note: "T82" },
  { id: "kelvvicl", name: "SONY 70-200MM F2.8 II", brand: "SONY", model: "70-200MM F2.8 II", department: "Lenses", subcategory: "Sony GM", note: "T77" },
  { id: "y30971vk", name: "SONY 14 MM F1.8", brand: "SONY", model: "14 MM F1.8", department: "Lenses", subcategory: "Sony GM", note: "" },
  { id: "on85vq8j", name: "SONY 24MM F1.4", brand: "SONY", model: "24MM F1.4", department: "Lenses", subcategory: "Sony GM", note: "T67" },
  { id: "74q2zfiy", name: "SONY 35MM F1.4", brand: "SONY", model: "35MM F1.4", department: "Lenses", subcategory: "Sony GM", note: "T67" },
  { id: "mz7gfqn1", name: "SONY 50MM F1.4", brand: "SONY", model: "50MM F1.4", department: "Lenses", subcategory: "Sony GM", note: "T67" },
  { id: "1s7hp9il", name: "SONY 50MM F1.2", brand: "SONY", model: "50MM F1.2", department: "Lenses", subcategory: "Sony GM", note: "T72" },
  { id: "2skjop1q", name: "SONY 85MM F1.4 II", brand: "SONY", model: "85MM F1.4 II", department: "Lenses", subcategory: "Sony GM", note: "T77" },
  { id: "f100pqpg", name: "SONY 90MM F2.8 MACRO OSS", brand: "SONY", model: "90MM F2.8 MACRO OSS", department: "Lenses", subcategory: "Sony GM", note: "T62" },
  { id: "uwub8sv5", name: "SONY 100MM F2.8 STF OSS", brand: "SONY", model: "100MM F2.8 STF OSS", department: "Lenses", subcategory: "Sony GM", note: "T72" },
  { id: "t3mp65cf", name: "ARRI 18K ARRIMAX", brand: "ARRI", model: "18K ARRIMAX", department: "Lighting", subcategory: "HMI", note: "" },
  { id: "rleprcjq", name: "ARRI M90", brand: "ARRI", model: "M90", department: "Lighting", subcategory: "HMI", note: "" },
  { id: "iboo6kmq", name: "ARRI M40", brand: "ARRI", model: "M40", department: "Lighting", subcategory: "HMI", note: "" },
  { id: "7gm4o7x0", name: "ARRI M18", brand: "ARRI", model: "M18", department: "Lighting", subcategory: "HMI", note: "" },
  { id: "ztc27am5", name: "12K", brand: "", model: "12K", department: "Lighting", subcategory: "HMI", note: "" },
  { id: "m4v7vzts", name: "6K", brand: "", model: "6K", department: "Lighting", subcategory: "HMI", note: "" },
  { id: "03cme6gd", name: "6KW FRESNEL", brand: "", model: "6KW FRESNEL", department: "Lighting", subcategory: "HMI", note: "" },
  { id: "hvo1mz4h", name: "4KW FRESNEL", brand: "", model: "4KW FRESNEL", department: "Lighting", subcategory: "HMI", note: "" },
  { id: "ty8d821z", name: "2.5KW FRESNEL", brand: "", model: "2.5KW FRESNEL", department: "Lighting", subcategory: "HMI", note: "" },
  { id: "oajczzco", name: "1.2KW FRESNEL", brand: "", model: "1.2KW FRESNEL", department: "Lighting", subcategory: "HMI", note: "" },
  { id: "2szyh7iv", name: "10K FRESNEL", brand: "", model: "10K FRESNEL", department: "Lighting", subcategory: "Tungsten", note: "" },
  { id: "ewm4f6dy", name: "5K FRESNEL", brand: "", model: "5K FRESNEL", department: "Lighting", subcategory: "Tungsten", note: "" },
  { id: "9o5utxfs", name: "2K FRESNEL", brand: "", model: "2K FRESNEL", department: "Lighting", subcategory: "Tungsten", note: "" },
  { id: "d3h4oof4", name: "2K BLONDIE", brand: "", model: "2K BLONDIE", department: "Lighting", subcategory: "Tungsten", note: "" },
  { id: "b3jxh26r", name: "1K FRESNEL", brand: "", model: "1K FRESNEL", department: "Lighting", subcategory: "Tungsten", note: "" },
  { id: "8c73lai0", name: "1KW PARCAN", brand: "", model: "1KW PARCAN", department: "Lighting", subcategory: "Tungsten", note: "" },
  { id: "rzrv93ty", name: "800W REDHEAD", brand: "", model: "800W REDHEAD", department: "Lighting", subcategory: "Tungsten", note: "" },
  { id: "wlo0icy5", name: "650W", brand: "", model: "650W", department: "Lighting", subcategory: "Tungsten", note: "" },
  { id: "oaggrnrb", name: "DEDOLIGHT 150", brand: "DEDOLIGHT", model: "150", department: "Lighting", subcategory: "Tungsten", note: "Set" },
  { id: "px4nsrx8", name: "MAXIBRUTE", brand: "", model: "MAXIBRUTE", department: "Lighting", subcategory: "Tungsten", note: "" },
  { id: "rrqu57tf", name: "SPACELIGHT", brand: "", model: "SPACELIGHT", department: "Lighting", subcategory: "Tungsten", note: "" },
  { id: "jftxiupc", name: "SKYPANEL S30", brand: "SKYPANEL", model: "S30", department: "Lighting", subcategory: "LED", note: "" },
  { id: "gklsacfr", name: "SKYPANEL S60", brand: "SKYPANEL", model: "S60", department: "Lighting", subcategory: "LED", note: "" },
  { id: "3k2o922r", name: "SKYPANEL S120", brand: "SKYPANEL", model: "S120", department: "Lighting", subcategory: "LED", note: "" },
  { id: "jiu9e1sr", name: "SKYPANEL S360", brand: "SKYPANEL", model: "S360", department: "Lighting", subcategory: "LED", note: "" },
  { id: "dkjn9fn5", name: "APUTURE STORM XT52", brand: "APUTURE", model: "STORM XT52", department: "Lighting", subcategory: "LED", note: "" },
  { id: "vt5lu359", name: "APUTURE STORM XT26", brand: "APUTURE", model: "STORM XT26", department: "Lighting", subcategory: "LED", note: "" },
  { id: "u7sn6alk", name: "APUTURE STORM CS32", brand: "APUTURE", model: "STORM CS32", department: "Lighting", subcategory: "LED", note: "" },
  { id: "nnkwiaj7", name: "APUTURE STORM CS15", brand: "APUTURE", model: "STORM CS15", department: "Lighting", subcategory: "LED", note: "" },
  { id: "13rcup0t", name: "APUTURE STORM 1200X", brand: "APUTURE", model: "STORM 1200X", department: "Lighting", subcategory: "LED", note: "" },
  { id: "167kce4g", name: "APUTURE STORM 1000C", brand: "APUTURE", model: "STORM 1000C", department: "Lighting", subcategory: "LED", note: "" },
  { id: "9kyf8w4r", name: "APUTURE LS 600C PRO II", brand: "APUTURE", model: "LS 600C PRO II", department: "Lighting", subcategory: "LED", note: "" },
  { id: "0bxsknq4", name: "APUTURE LS 300D II", brand: "", model: "APUTURE LS 300D II", department: "Lighting", subcategory: "LED", note: "" },
  { id: "2hgfxwlu", name: "APUTURE STORM 80C", brand: "APUTURE", model: "STORM 80C", department: "Lighting", subcategory: "LED", note: "" },
  { id: "nqowu7hm", name: "APUTURE NOVA P600C", brand: "APUTURE", model: "NOVA P600C", department: "Lighting", subcategory: "LED", note: "" },
  { id: "4cipcela", name: "APUTURE NOVA P300C", brand: "APUTURE", model: "NOVA P300C", department: "Lighting", subcategory: "LED", note: "" },
  { id: "y33rohqa", name: "APUTURE NOVA 9°", brand: "APUTURE", model: "NOVA 9°", department: "Lighting", subcategory: "LED", note: "" },
  { id: "7lr7xjhv", name: "APUTURE NOVA II", brand: "APUTURE", model: "NOVA II", department: "Lighting", subcategory: "LED", note: "" },
  { id: "19kgbp1y", name: "APUTURE MC PRO", brand: "APUTURE", model: "MC PRO", department: "Lighting", subcategory: "LED", note: "Kit 8" },
  { id: "lwyu6ath", name: "APUTURE ACCENT B7C", brand: "APUTURE", model: "ACCENT B7C", department: "Lighting", subcategory: "LED", note: "Kit 8" },
  { id: "lrs3v5yg", name: "APUTURE INFINIMAT 4X4", brand: "APUTURE", model: "INFINIMAT 4X4", department: "Lighting", subcategory: "LED", note: "" },
  { id: "4o5kju18", name: "APUTURE INFINIMAT 8X8", brand: "APUTURE", model: "INFINIMAT 8X8", department: "Lighting", subcategory: "LED", note: "" },
  { id: "bnt9cokj", name: "AMARAN F22", brand: "AMARAN", model: "F22", department: "Lighting", subcategory: "LED", note: "" },
  { id: "2ay0zzi3", name: "AMARAN F21", brand: "AMARAN", model: "F21", department: "Lighting", subcategory: "LED", note: "" },
  { id: "50w5eqst", name: "APUTURE PB3", brand: "APUTURE", model: "PB3", department: "Lighting", subcategory: "LED", note: "" },
  { id: "2fw7t57o", name: "APUTURE PB6", brand: "APUTURE", model: "PB6", department: "Lighting", subcategory: "LED", note: "" },
  { id: "v2v83m3x", name: "APUTURE PB12", brand: "APUTURE", model: "PB12", department: "Lighting", subcategory: "LED", note: "" },
  { id: "hk0z6sbw", name: "AMARAN PT2C", brand: "AMARAN", model: "PT2C", department: "Lighting", subcategory: "LED", note: "" },
  { id: "soi8ir5r", name: "AMARAN PT4C", brand: "AMARAN", model: "PT4C", department: "Lighting", subcategory: "LED", note: "" },
  { id: "zsxwgcj1", name: "PDL MAXI 6 BÓNG", brand: "PDL", model: "MAXI 6 BÓNG", department: "Lighting", subcategory: "LED", note: "" },
  { id: "fm5wyso1", name: "PDL MAXI 6 BÓNG RGB", brand: "PDL", model: "MAXI 6 BÓNG RGB", department: "Lighting", subcategory: "LED", note: "" },
  { id: "yl0svu5l", name: "PDL MAXI 9 BÓNG", brand: "PDL", model: "MAXI 9 BÓNG", department: "Lighting", subcategory: "LED", note: "" },
  { id: "cv8s48h5", name: "PDL MAXI 12 BÓNG", brand: "PDL", model: "MAXI 12 BÓNG", department: "Lighting", subcategory: "LED", note: "" },
  { id: "2mqkltuu", name: "LIGHT DOME 40", brand: "", model: "LIGHT DOME 40", department: "Lighting", subcategory: "Modifiers", note: "" },
  { id: "2sz8vguv", name: "LIGHT DOME 60", brand: "", model: "LIGHT DOME 60", department: "Lighting", subcategory: "Modifiers", note: "" },
  { id: "5rpzizjh", name: "LIGHT DOME 90", brand: "", model: "LIGHT DOME 90", department: "Lighting", subcategory: "Modifiers", note: "" },
  { id: "nxran5i4", name: "LIGHT DOME 120", brand: "", model: "LIGHT DOME 120", department: "Lighting", subcategory: "Modifiers", note: "" },
  { id: "ig628mqb", name: "LIGHT DOME 150", brand: "", model: "LIGHT DOME 150", department: "Lighting", subcategory: "Modifiers", note: "" },
  { id: "33a2x7v1", name: "APUTURE CF16 FRESNEL", brand: "APUTURE", model: "CF16 FRESNEL", department: "Lighting", subcategory: "Modifiers", note: "" },
  { id: "06oa5unh", name: "APUTURE F14 FRESNEL", brand: "APUTURE", model: "F14 FRESNEL", department: "Lighting", subcategory: "Modifiers", note: "" },
  { id: "agi4s07s", name: "APUTURE F10 FRESNEL", brand: "APUTURE", model: "F10 FRESNEL", department: "Lighting", subcategory: "Modifiers", note: "" },
  { id: "pnvts5p3", name: "APUTURE LANTERN", brand: "APUTURE", model: "LANTERN", department: "Lighting", subcategory: "Modifiers", note: "60cm 90cm 120cm 180cm" },
  { id: "xzxzide1", name: "APUTURE SPOTLIGHT MAX", brand: "APUTURE", model: "SPOTLIGHT MAX", department: "Lighting", subcategory: "Modifiers", note: "19° 36° 50°" },
  { id: "ewa0t1yd", name: "APUTURE SPOTLIGHT MOUNT", brand: "APUTURE", model: "SPOTLIGHT MOUNT", department: "Lighting", subcategory: "Modifiers", note: "19° 26° 36°" },
  { id: "g9nygxpi", name: "SET FRAME 8X8", brand: "", model: "SET FRAME 8X8", department: "Lighting", subcategory: "Modifiers", note: "Silk/Ultrabounce/Black" },
  { id: "1nimzhsf", name: "SET FRAME 12X12", brand: "", model: "SET FRAME 12X12", department: "Lighting", subcategory: "Modifiers", note: "Silk/Ultrabounce/Black" },
  { id: "j8bqd719", name: "SET FRAME 20X20", brand: "", model: "SET FRAME 20X20", department: "Lighting", subcategory: "Modifiers", note: "Silk/Ultrabounce/Black" },
  { id: "zpgsx4ri", name: "SILK", brand: "", model: "SILK", department: "Lighting", subcategory: "Modifiers", note: "" },
  { id: "89kdzp2l", name: "PHẢN QUANG GƯƠNG", brand: "", model: "PHẢN QUANG GƯƠNG", department: "Lighting", subcategory: "Special", note: "Silver/white 4x4" },
  { id: "o7dp86wf", name: "CHROMA KEY GREEN", brand: "", model: "CHROMA KEY GREEN", department: "Lighting", subcategory: "Special", note: "" },
  { id: "9scj6sfh", name: "CHROMA KEY BLUE", brand: "", model: "CHROMA KEY BLUE", department: "Lighting", subcategory: "Special", note: "" },
  { id: "f05hqkf8", name: "GENERATOR TRUCK", brand: "", model: "GENERATOR TRUCK", department: "Others", subcategory: "Cinema Bodies", note: "" },
  { id: "mimhtkrq", name: "HOLLYLAND SOLIDCOM C1 PRO", brand: "HOLLYLAND", model: "SOLIDCOM C1 PRO", department: "Others", subcategory: "Cinema Bodies", note: "" },
  { id: "9vj5dil2", name: "INTERCOM SET", brand: "", model: "INTERCOM SET", department: "Others", subcategory: "Cinema Bodies", note: "" },
];


export const DEFAULT_PROJECT_TAGS = ["TVC", "MV", "Short"];

export const QTY_OPTIONS = Array.from({ length: 100 }, (_, i) => i); // 0-99


// 8 accent essences, each with a light-mode and dark-mode shade tuned for
// contrast against that mode's background (light shades are darker/more
// saturated; dark shades are brighter, since the background flips).
export const ACCENT_CHOICES = [
  { id: "amber", name: "Amber", light: "#B8790A", dark: "#FFB020" },
  { id: "crimson", name: "Crimson", light: "#B23A3A", dark: "#FF5C5C" },
  { id: "teal", name: "Teal", light: "#0F766E", dark: "#2DD4BF" },
  { id: "blue", name: "Blue", light: "#1D4ED8", dark: "#5B9DFF" },
  { id: "violet", name: "Violet", light: "#7C3AED", dark: "#A78BFA" },
  { id: "green", name: "Green", light: "#15803D", dark: "#4ADE80" },
  { id: "pink", name: "Pink", light: "#BE185D", dark: "#F472B6" },
  { id: "slate", name: "Slate", light: "#404040", dark: "#B0B0B0" },
];


// 5 curated fonts, all with solid Vietnamese diacritic support.
// App-wide size, chosen per device (saved in that browser, not the account).
// Scales the whole app — text, buttons, icons — never the PDF or share page.
export const UI_SIZES = [
  { id: "small", name: "Small", zoom: 0.9 },
  { id: "normal", name: "Normal", zoom: 1 },
  { id: "large", name: "Large", zoom: 1.15 },
];

export const FONT_CHOICES = [
  { id: "jetbrains", name: "JetBrains Mono", stack: "'JetBrains Mono', ui-monospace, 'SF Mono', Menlo, monospace", googleFamily: "JetBrains+Mono:wght@400;500;600;700" },
  { id: "plex", name: "IBM Plex Mono", stack: "'IBM Plex Mono', ui-monospace, 'SF Mono', Menlo, monospace", googleFamily: "IBM+Plex+Mono:wght@400;500;600;700" },
  { id: "roboto", name: "Roboto Mono", stack: "'Roboto Mono', ui-monospace, 'SF Mono', Menlo, monospace", googleFamily: "Roboto+Mono:wght@400;500;600;700" },
  { id: "source", name: "Source Code Pro", stack: "'Source Code Pro', ui-monospace, 'SF Mono', Menlo, monospace", googleFamily: "Source+Code+Pro:wght@400;500;600;700" },
  { id: "inter", name: "Inter", stack: "'Inter', ui-sans-serif, system-ui, sans-serif", googleFamily: "Inter:wght@400;500;600;700" },
];
